# FeatherCatMonitor by Zerek

# Ping players when their name is said in chat.
# Warn and kick spamming players
# Color messages prefixed with a 'distinguish' tag.
# sound names https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# FORMAT: ping: Sound sound, float volume, float pitch
ping:
  sound: "BLOCK_NOTE_BLOCK_HARP"
  volume: 1.0
  pitch: 1.0

spam-limit:
  messages:
    second-count: 10
    message-count: 6
  warnings:
    second-count: 60
    message-count: 4
    warning: "<red>You are spamming - please slow down or you will be kicked."
    kick-message: "<red>Automatically kicked for spamming."

distinguish:
  tag: "<distinguish>"
  groups:
    # Take care to ensure no player is a member of two groups which share a priority level.
    donor:
      priority: 1
      color: "#FAECA7"
    assistant:
      priority: 2
      color: "#6EABFF"
    moderator:
      priority: 3
      color: "#49DB44"
    administrator:
      priority: 4
      color: "#F51657"