#FeatherCatMonitor by Zerek

#Ping players when their name is said in chat.
#sound names https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
#FORMAT: ping: Sound sound, float volume, float pitch
ping:
  sound: "BLOCK_NOTE_BLOCK_HARP"
  volume: 1.0
  pitch: 1.0

spam-limit:
  messages:
    second-count: 10
    message-count: 6
  warnings:
    second-count: 60
    message-count: 4
    warning: "<red>You are spamming - please slow down or you will be kicked."
    kick-message: "<red>Automatically kicked for spamming chat."